/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ControlRouteImport } from './routes/control'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LauncherLoginRouteImport } from './routes/launcher-login'
import { Route as LauncherSetupRouteImport } from './routes/launcher-setup'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as AgentAutomationsRouteImport } from './routes/agent/automations'
import { Route as AgentHubRouteImport } from './routes/agent/hub'
import { Route as AgentMonitorRouteImport } from './routes/agent/monitor'
import { Route as AgentRunRouteImport } from './routes/agent/run'
import { Route as AgentRunsRouteImport } from './routes/agent/runs'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as AgentsSwarmRouteImport } from './routes/agents.swarm'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PluginsCapabilitiesRouteImport } from './routes/plugins.capabilities'
import { Route as PluginsCatalogRouteImport } from './routes/plugins.catalog'
import { Route as PluginsChannelsRouteImport } from './routes/plugins.channels'
import { Route as PluginsCoreRouteImport } from './routes/plugins.core'
import { Route as PluginsHealthRouteImport } from './routes/plugins.health'
import { Route as PluginsProvidersRouteImport } from './routes/plugins.providers'
import { Route as AgentAutomationsIndexRouteImport } from './routes/agent/automations.index'
import { Route as AgentAutomationsConnectionsRouteImport } from './routes/agent/automations.connections'
import { Route as AgentAutomationsCreateRouteImport } from './routes/agent/automations.create'
import { Route as AgentAutomationsHistoryRouteImport } from './routes/agent/automations.history'
import { Route as AgentAutomationsListRouteImport } from './routes/agent/automations.list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherLoginRoute = LauncherLoginRouteImport.update({
  id: '/launcher-login',
  path: '/launcher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSetupRoute = LauncherSetupRouteImport.update({
  id: '/launcher-setup',
  path: '/launcher-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAutomationsRoute = AgentAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AgentRoute,
} as any)
const AgentHubRoute = AgentHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMonitorRoute = AgentMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => AgentRoute,
} as any)
const AgentRunRoute = AgentRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => AgentRoute,
} as any)
const AgentRunsRoute = AgentRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsSwarmRoute = AgentsSwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => AgentsRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsCapabilitiesRoute = PluginsCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsCatalogRoute = PluginsCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsChannelsRoute = PluginsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsCoreRoute = PluginsCoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsHealthRoute = PluginsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => PluginsRoute,
} as any)
const PluginsProvidersRoute = PluginsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => PluginsRoute,
} as any)
const AgentAutomationsIndexRoute = AgentAutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentAutomationsRoute,
} as any)
const AgentAutomationsConnectionsRoute =
  AgentAutomationsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AgentAutomationsRoute,
  } as any)
const AgentAutomationsCreateRoute = AgentAutomationsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AgentAutomationsRoute,
} as any)
const AgentAutomationsHistoryRoute = AgentAutomationsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AgentAutomationsRoute,
} as any)
const AgentAutomationsListRoute = AgentAutomationsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AgentAutomationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agent': typeof AgentRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRouteWithChildren
  '/control': typeof ControlRoute
  '/credentials': typeof CredentialsRoute
  '/drive': typeof DriveRoute
  '/health': typeof HealthRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/agent/automations': typeof AgentAutomationsRouteWithChildren
  '/agent/hub': typeof AgentHubRoute
  '/agent/monitor': typeof AgentMonitorRoute
  '/agent/run': typeof AgentRunRoute
  '/agent/runs': typeof AgentRunsRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/swarm': typeof AgentsSwarmRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/plugins/capabilities': typeof PluginsCapabilitiesRoute
  '/plugins/catalog': typeof PluginsCatalogRoute
  '/plugins/channels': typeof PluginsChannelsRoute
  '/plugins/core': typeof PluginsCoreRoute
  '/plugins/health': typeof PluginsHealthRoute
  '/plugins/providers': typeof PluginsProvidersRoute
  '/agents/': typeof AgentsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/agent/automations/connections': typeof AgentAutomationsConnectionsRoute
  '/agent/automations/create': typeof AgentAutomationsCreateRoute
  '/agent/automations/history': typeof AgentAutomationsHistoryRoute
  '/agent/automations/list': typeof AgentAutomationsListRoute
  '/agent/automations/': typeof AgentAutomationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agent': typeof AgentRouteWithChildren
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRouteWithChildren
  '/control': typeof ControlRoute
  '/credentials': typeof CredentialsRoute
  '/drive': typeof DriveRoute
  '/health': typeof HealthRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/agent/hub': typeof AgentHubRoute
  '/agent/monitor': typeof AgentMonitorRoute
  '/agent/run': typeof AgentRunRoute
  '/agent/runs': typeof AgentRunsRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/swarm': typeof AgentsSwarmRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/plugins/capabilities': typeof PluginsCapabilitiesRoute
  '/plugins/catalog': typeof PluginsCatalogRoute
  '/plugins/channels': typeof PluginsChannelsRoute
  '/plugins/core': typeof PluginsCoreRoute
  '/plugins/health': typeof PluginsHealthRoute
  '/plugins/providers': typeof PluginsProvidersRoute
  '/agents': typeof AgentsIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/agent/automations/connections': typeof AgentAutomationsConnectionsRoute
  '/agent/automations/create': typeof AgentAutomationsCreateRoute
  '/agent/automations/history': typeof AgentAutomationsHistoryRoute
  '/agent/automations/list': typeof AgentAutomationsListRoute
  '/agent/automations': typeof AgentAutomationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agent': typeof AgentRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/config': typeof ConfigRouteWithChildren
  '/control': typeof ControlRoute
  '/credentials': typeof CredentialsRoute
  '/drive': typeof DriveRoute
  '/health': typeof HealthRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/agent/automations': typeof AgentAutomationsRouteWithChildren
  '/agent/hub': typeof AgentHubRoute
  '/agent/monitor': typeof AgentMonitorRoute
  '/agent/run': typeof AgentRunRoute
  '/agent/runs': typeof AgentRunsRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/agents/swarm': typeof AgentsSwarmRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/plugins/capabilities': typeof PluginsCapabilitiesRoute
  '/plugins/catalog': typeof PluginsCatalogRoute
  '/plugins/channels': typeof PluginsChannelsRoute
  '/plugins/core': typeof PluginsCoreRoute
  '/plugins/health': typeof PluginsHealthRoute
  '/plugins/providers': typeof PluginsProvidersRoute
  '/agents/': typeof AgentsIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/agent/automations/connections': typeof AgentAutomationsConnectionsRoute
  '/agent/automations/create': typeof AgentAutomationsCreateRoute
  '/agent/automations/history': typeof AgentAutomationsHistoryRoute
  '/agent/automations/list': typeof AgentAutomationsListRoute
  '/agent/automations/': typeof AgentAutomationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/about'
    | '/agent'
    | '/agents'
    | '/chat'
    | '/config'
    | '/control'
    | '/credentials'
    | '/drive'
    | '/health'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/memory'
    | '/models'
    | '/plugins'
    | '/agent/automations'
    | '/agent/hub'
    | '/agent/monitor'
    | '/agent/run'
    | '/agent/runs'
    | '/agent/skills'
    | '/agent/tools'
    | '/agents/$id'
    | '/agents/swarm'
    | '/channels/$name'
    | '/config/raw'
    | '/plugins/capabilities'
    | '/plugins/catalog'
    | '/plugins/channels'
    | '/plugins/core'
    | '/plugins/health'
    | '/plugins/providers'
    | '/agents/'
    | '/plugins/'
    | '/agent/automations/connections'
    | '/agent/automations/create'
    | '/agent/automations/history'
    | '/agent/automations/list'
    | '/agent/automations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/about'
    | '/agent'
    | '/chat'
    | '/config'
    | '/control'
    | '/credentials'
    | '/drive'
    | '/health'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/memory'
    | '/models'
    | '/agent/hub'
    | '/agent/monitor'
    | '/agent/run'
    | '/agent/runs'
    | '/agent/skills'
    | '/agent/tools'
    | '/agents/$id'
    | '/agents/swarm'
    | '/channels/$name'
    | '/config/raw'
    | '/plugins/capabilities'
    | '/plugins/catalog'
    | '/plugins/channels'
    | '/plugins/core'
    | '/plugins/health'
    | '/plugins/providers'
    | '/agents'
    | '/plugins'
    | '/agent/automations/connections'
    | '/agent/automations/create'
    | '/agent/automations/history'
    | '/agent/automations/list'
    | '/agent/automations'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/about'
    | '/agent'
    | '/agents'
    | '/chat'
    | '/config'
    | '/control'
    | '/credentials'
    | '/drive'
    | '/health'
    | '/launcher-login'
    | '/launcher-setup'
    | '/logs'
    | '/memory'
    | '/models'
    | '/plugins'
    | '/agent/automations'
    | '/agent/hub'
    | '/agent/monitor'
    | '/agent/run'
    | '/agent/runs'
    | '/agent/skills'
    | '/agent/tools'
    | '/agents/$id'
    | '/agents/swarm'
    | '/channels/$name'
    | '/config/raw'
    | '/plugins/capabilities'
    | '/plugins/catalog'
    | '/plugins/channels'
    | '/plugins/core'
    | '/plugins/health'
    | '/plugins/providers'
    | '/agents/'
    | '/plugins/'
    | '/agent/automations/connections'
    | '/agent/automations/create'
    | '/agent/automations/history'
    | '/agent/automations/list'
    | '/agent/automations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgentRoute: typeof AgentRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  ChatRoute: typeof ChatRoute
  ConfigRoute: typeof ConfigRouteWithChildren
  ControlRoute: typeof ControlRoute
  CredentialsRoute: typeof CredentialsRoute
  DriveRoute: typeof DriveRoute
  HealthRoute: typeof HealthRoute
  LauncherLoginRoute: typeof LauncherLoginRoute
  LauncherSetupRoute: typeof LauncherSetupRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  PluginsRoute: typeof PluginsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-login': {
      id: '/launcher-login'
      path: '/launcher-login'
      fullPath: '/launcher-login'
      preLoaderRoute: typeof LauncherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-setup': {
      id: '/launcher-setup'
      path: '/launcher-setup'
      fullPath: '/launcher-setup'
      preLoaderRoute: typeof LauncherSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/automations': {
      id: '/agent/automations'
      path: '/automations'
      fullPath: '/agent/automations'
      preLoaderRoute: typeof AgentAutomationsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/hub': {
      id: '/agent/hub'
      path: '/hub'
      fullPath: '/agent/hub'
      preLoaderRoute: typeof AgentHubRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/monitor': {
      id: '/agent/monitor'
      path: '/monitor'
      fullPath: '/agent/monitor'
      preLoaderRoute: typeof AgentMonitorRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/run': {
      id: '/agent/run'
      path: '/run'
      fullPath: '/agent/run'
      preLoaderRoute: typeof AgentRunRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/runs': {
      id: '/agent/runs'
      path: '/runs'
      fullPath: '/agent/runs'
      preLoaderRoute: typeof AgentRunsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/swarm': {
      id: '/agents/swarm'
      path: '/swarm'
      fullPath: '/agents/swarm'
      preLoaderRoute: typeof AgentsSwarmRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/plugins/capabilities': {
      id: '/plugins/capabilities'
      path: '/capabilities'
      fullPath: '/plugins/capabilities'
      preLoaderRoute: typeof PluginsCapabilitiesRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/plugins/catalog': {
      id: '/plugins/catalog'
      path: '/catalog'
      fullPath: '/plugins/catalog'
      preLoaderRoute: typeof PluginsCatalogRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/plugins/channels': {
      id: '/plugins/channels'
      path: '/channels'
      fullPath: '/plugins/channels'
      preLoaderRoute: typeof PluginsChannelsRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/plugins/core': {
      id: '/plugins/core'
      path: '/core'
      fullPath: '/plugins/core'
      preLoaderRoute: typeof PluginsCoreRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/plugins/health': {
      id: '/plugins/health'
      path: '/health'
      fullPath: '/plugins/health'
      preLoaderRoute: typeof PluginsHealthRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/plugins/providers': {
      id: '/plugins/providers'
      path: '/providers'
      fullPath: '/plugins/providers'
      preLoaderRoute: typeof PluginsProvidersRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/agent/automations/': {
      id: '/agent/automations/'
      path: '/'
      fullPath: '/agent/automations/'
      preLoaderRoute: typeof AgentAutomationsIndexRouteImport
      parentRoute: typeof AgentAutomationsRoute
    }
    '/agent/automations/connections': {
      id: '/agent/automations/connections'
      path: '/connections'
      fullPath: '/agent/automations/connections'
      preLoaderRoute: typeof AgentAutomationsConnectionsRouteImport
      parentRoute: typeof AgentAutomationsRoute
    }
    '/agent/automations/create': {
      id: '/agent/automations/create'
      path: '/create'
      fullPath: '/agent/automations/create'
      preLoaderRoute: typeof AgentAutomationsCreateRouteImport
      parentRoute: typeof AgentAutomationsRoute
    }
    '/agent/automations/history': {
      id: '/agent/automations/history'
      path: '/history'
      fullPath: '/agent/automations/history'
      preLoaderRoute: typeof AgentAutomationsHistoryRouteImport
      parentRoute: typeof AgentAutomationsRoute
    }
    '/agent/automations/list': {
      id: '/agent/automations/list'
      path: '/list'
      fullPath: '/agent/automations/list'
      preLoaderRoute: typeof AgentAutomationsListRouteImport
      parentRoute: typeof AgentAutomationsRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface AgentAutomationsRouteChildren {
  AgentAutomationsConnectionsRoute: typeof AgentAutomationsConnectionsRoute
  AgentAutomationsCreateRoute: typeof AgentAutomationsCreateRoute
  AgentAutomationsHistoryRoute: typeof AgentAutomationsHistoryRoute
  AgentAutomationsListRoute: typeof AgentAutomationsListRoute
  AgentAutomationsIndexRoute: typeof AgentAutomationsIndexRoute
}

const AgentAutomationsRouteChildren: AgentAutomationsRouteChildren = {
  AgentAutomationsConnectionsRoute: AgentAutomationsConnectionsRoute,
  AgentAutomationsCreateRoute: AgentAutomationsCreateRoute,
  AgentAutomationsHistoryRoute: AgentAutomationsHistoryRoute,
  AgentAutomationsListRoute: AgentAutomationsListRoute,
  AgentAutomationsIndexRoute: AgentAutomationsIndexRoute,
}

const AgentAutomationsRouteWithChildren =
  AgentAutomationsRoute._addFileChildren(AgentAutomationsRouteChildren)

interface AgentRouteChildren {
  AgentAutomationsRoute: typeof AgentAutomationsRouteWithChildren
  AgentHubRoute: typeof AgentHubRoute
  AgentMonitorRoute: typeof AgentMonitorRoute
  AgentRunRoute: typeof AgentRunRoute
  AgentRunsRoute: typeof AgentRunsRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAutomationsRoute: AgentAutomationsRouteWithChildren,
  AgentHubRoute: AgentHubRoute,
  AgentMonitorRoute: AgentMonitorRoute,
  AgentRunRoute: AgentRunRoute,
  AgentRunsRoute: AgentRunsRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsSwarmRoute: typeof AgentsSwarmRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsSwarmRoute: AgentsSwarmRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface PluginsRouteChildren {
  PluginsCapabilitiesRoute: typeof PluginsCapabilitiesRoute
  PluginsCatalogRoute: typeof PluginsCatalogRoute
  PluginsChannelsRoute: typeof PluginsChannelsRoute
  PluginsCoreRoute: typeof PluginsCoreRoute
  PluginsHealthRoute: typeof PluginsHealthRoute
  PluginsProvidersRoute: typeof PluginsProvidersRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
}

const PluginsRouteChildren: PluginsRouteChildren = {
  PluginsCapabilitiesRoute: PluginsCapabilitiesRoute,
  PluginsCatalogRoute: PluginsCatalogRoute,
  PluginsChannelsRoute: PluginsChannelsRoute,
  PluginsCoreRoute: PluginsCoreRoute,
  PluginsHealthRoute: PluginsHealthRoute,
  PluginsProvidersRoute: PluginsProvidersRoute,
  PluginsIndexRoute: PluginsIndexRoute,
}

const PluginsRouteWithChildren =
  PluginsRoute._addFileChildren(PluginsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AgentRoute: AgentRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  ChatRoute: ChatRoute,
  ConfigRoute: ConfigRouteWithChildren,
  ControlRoute: ControlRoute,
  CredentialsRoute: CredentialsRoute,
  DriveRoute: DriveRoute,
  HealthRoute: HealthRoute,
  LauncherLoginRoute: LauncherLoginRoute,
  LauncherSetupRoute: LauncherSetupRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  PluginsRoute: PluginsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
