/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ControlRouteImport } from './routes/control'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LauncherLoginRouteImport } from './routes/launcher-login'
import { Route as LauncherSetupRouteImport } from './routes/launcher-setup'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as AgentMonitorRouteImport } from './routes/agent/monitor'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherLoginRoute = LauncherLoginRouteImport.update({
  id: '/launcher-login',
  path: '/launcher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LauncherSetupRoute = LauncherSetupRouteImport.update({
  id: '/launcher-setup',
  path: '/launcher-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMonitorRoute = AgentMonitorRouteImport.update({
  id: '/agent/monitor',
  path: '/agent/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/agent/skills',
  path: '/agent/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/agent/tools',
  path: '/agent/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/config': typeof ConfigRoute
  '/control': typeof ControlRoute
  '/drive': typeof DriveRoute
  '/health': typeof HealthRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/agent/monitor': typeof AgentMonitorRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/config': typeof ConfigRoute
  '/control': typeof ControlRoute
  '/drive': typeof DriveRoute
  '/health': typeof HealthRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/agent/monitor': typeof AgentMonitorRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/config': typeof ConfigRoute
  '/control': typeof ControlRoute
  '/drive': typeof DriveRoute
  '/health': typeof HealthRoute
  '/launcher-login': typeof LauncherLoginRoute
  '/launcher-setup': typeof LauncherSetupRoute
  '/memory': typeof MemoryRoute
  '/models': typeof ModelsRoute
  '/plugins': typeof PluginsRoute
  '/agent/monitor': typeof AgentMonitorRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/config'
    | '/control'
    | '/drive'
    | '/health'
    | '/launcher-login'
    | '/launcher-setup'
    | '/memory'
    | '/models'
    | '/plugins'
    | '/agent/monitor'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/config'
    | '/control'
    | '/drive'
    | '/health'
    | '/launcher-login'
    | '/launcher-setup'
    | '/memory'
    | '/models'
    | '/plugins'
    | '/agent/monitor'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/config'
    | '/control'
    | '/drive'
    | '/health'
    | '/launcher-login'
    | '/launcher-setup'
    | '/memory'
    | '/models'
    | '/plugins'
    | '/agent/monitor'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  ConfigRoute: typeof ConfigRoute
  ControlRoute: typeof ControlRoute
  DriveRoute: typeof DriveRoute
  HealthRoute: typeof HealthRoute
  LauncherLoginRoute: typeof LauncherLoginRoute
  LauncherSetupRoute: typeof LauncherSetupRoute
  MemoryRoute: typeof MemoryRoute
  ModelsRoute: typeof ModelsRoute
  PluginsRoute: typeof PluginsRoute
  AgentMonitorRoute: typeof AgentMonitorRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-login': {
      id: '/launcher-login'
      path: '/launcher-login'
      fullPath: '/launcher-login'
      preLoaderRoute: typeof LauncherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launcher-setup': {
      id: '/launcher-setup'
      path: '/launcher-setup'
      fullPath: '/launcher-setup'
      preLoaderRoute: typeof LauncherSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/monitor': {
      id: '/agent/monitor'
      path: '/agent/monitor'
      fullPath: '/agent/monitor'
      preLoaderRoute: typeof AgentMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/agent/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/agent/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  ConfigRoute: ConfigRoute,
  ControlRoute: ControlRoute,
  DriveRoute: DriveRoute,
  HealthRoute: HealthRoute,
  LauncherLoginRoute: LauncherLoginRoute,
  LauncherSetupRoute: LauncherSetupRoute,
  MemoryRoute: MemoryRoute,
  ModelsRoute: ModelsRoute,
  PluginsRoute: PluginsRoute,
  AgentMonitorRoute: AgentMonitorRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
