import { existsSync, readFileSync } from "node:fs"
import path from "node:path"

export interface ToolGroupStatus {
  key: string
  enabled: boolean
}

const CAPABILITY_TEXT: Record<string, string> = {
  terminal: "Terminal (terminal_run): run any shell command like a human operator — builds, git, package managers, scripts, system inspection.",
  browser: "Browser (browser_*): open pages, click, type, extract content and take screenshots in a real browser.",
  web_search: "Web search (web_search): look up current information on the web and cite the results.",
  filesystem: "Files (file_*, workspace_*): read, search, write, move, copy and delete files.",
  memory: "Memory (memory_*): store and recall long-term notes.",
  skills: "Skills (skill_*): discover, read, run and install skills.",
  goals: "Goals (goal_*): keep persistent goals across runs.",
  control: "Agent control (agent_control_*): inspect and change your own configuration.",
  computer: "Computer use (computer_*): observe and operate desktop windows and apps.",
}

const GROUP_ORDER = ["terminal", "browser", "web_search", "filesystem", "memory", "skills", "goals", "control", "computer"]

const IDENTITY_FILES = ["SOUL.md", "IDENTITY.md", "AGENTS.md", "USER.md"]

function readIdentityFiles(dirs: string[]): string {
  const dir = dirs.find((candidate) => existsSync(candidate))
  if (!dir) return ""
  const parts: string[] = []
  for (const file of IDENTITY_FILES) {
    try {
      const text = readFileSync(path.join(dir, file), "utf8").trim()
      if (text) parts.push(`[${file.replace(/\.md$/, "")}]\n${text}`)
    } catch {
      /* missing file is fine */
    }
  }
  return parts.join("\n\n")
}

/**
 * Context for Miki's system prompt: who it is, what it can do right now and
 * what is switched off. It is context only — the reply itself is always
 * generated by the model from this and the conversation.
 */
export function buildIdentityContext(input: {
  groups: ToolGroupStatus[]
  persona?: string
  identityDirs?: string[]
}): string {
  const status = new Map(input.groups.map((group) => [group.key, group.enabled]))
  const known = GROUP_ORDER.filter((key) => status.has(key))
  const on = known.filter((key) => status.get(key))
  const off = known.filter((key) => !status.get(key))
  const lines: string[] = [
    "IDENTITY: You are Miki, an autonomous AI agent (not just a chat assistant). You work like a capable human operator on the user's computer: understand the goal, plan, use tools, check the results, recover from failures and report honestly.",
  ]
  if (on.length) lines.push(`CAPABILITIES ENABLED NOW:\n${on.map((key) => `- ${CAPABILITY_TEXT[key]}`).join("\n")}`)
  if (off.length) lines.push(`CAPABILITIES CURRENTLY OFF (tell the user they can enable them in the Tools page if needed): ${off.join(", ")}.`)
  lines.push("Use tools whenever they get the job done better than guessing — run commands, browse and search instead of saying you cannot. Verify results before claiming success.")
  const persona = input.persona?.trim()
  if (persona) lines.push(`PERSONA:\n${persona}`)
  const files = readIdentityFiles(input.identityDirs ?? [])
  if (files) lines.push(files)
  return lines.join("\n\n")
}
